name: 'Gemini Code Security Reviewer'
description: 'AI-powered security review GitHub Action using Gemini CLI custom commands'
author: 'Community'

inputs:
  comment-pr:
    description: 'Whether to comment on PRs with findings'
    required: false
    default: 'true'

  upload-results:
    description: 'Whether to upload results as artifacts'
    required: false
    default: 'true'

  geminicli-timeout:
    description: 'Timeout for Gemini CLI analysis in minutes'
    required: false
    default: '20'

  gemini-api-key:
    description: 'Google Gemini API key'
    required: false
    default: ''

  gemini-model:
    description: 'Gemini model to use (e.g., gemini-2.5-pro, gemini-2.0-flash)'
    required: false
    default: ''

  run-every-commit:
    description: 'Run on every commit (skips cache check). Warning: may increase false positives on PRs with many commits.'
    required: false
    default: 'false'

outputs:
  findings-count:
    description: 'Number of security findings (HIGH + MEDIUM)'
    value: ${{ steps.geminicli-scan.outputs.findings_count }}

  results-file:
    description: 'Path to the results markdown file'
    value: ${{ steps.geminicli-scan.outputs.results_file || steps.use-cache.outputs.results_file }}

runs:
  using: 'composite'
  steps:
    - name: Install Node.js (for Gemini CLI)
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Gemini CLI
      shell: bash
      run: npm install -g @google/gemini-cli

    - name: Install security-review custom command
      shell: bash
      run: |
        mkdir -p ~/.gemini/commands
        cp ${{ github.action_path }}/.gemini/commands/security-review.toml ~/.gemini/commands/security-review.toml

    - name: Check for cached results
      id: check-cache
      shell: bash
      run: |
        if [ "${{ inputs.run-every-commit }}" = "true" ]; then
          echo "cache_hit=false" >> $GITHUB_OUTPUT
        else
          CACHE_KEY="${{ github.event.pull_request.number }}-${{ github.event.pull_request.head.sha }}"
          CACHE_FILE="/tmp/gemini-security-review-${CACHE_KEY}.md"
          if [ -f "$CACHE_FILE" ]; then
            echo "cache_hit=true" >> $GITHUB_OUTPUT
            echo "cache_file=$CACHE_FILE" >> $GITHUB_OUTPUT
          else
            echo "cache_hit=false" >> $GITHUB_OUTPUT
            echo "cache_file=$CACHE_FILE" >> $GITHUB_OUTPUT
          fi
        fi

    - name: Run Gemini CLI Security Scan
      id: geminicli-scan
      if: steps.check-cache.outputs.cache_hit != 'true'
      shell: bash
      env:
        GEMINI_API_KEY: ${{ inputs.gemini-api-key }}
      run: |
        RESULTS_FILE="/tmp/gemini-security-review-${{ github.event.pull_request.number }}-${{ github.event.pull_request.head.sha }}.md"

        MODEL_ARG=""
        if [ -n "${{ inputs.gemini-model }}" ]; then
          MODEL_ARG="--model ${{ inputs.gemini-model }}"
        fi

        cd ${{ github.workspace }}
        timeout $(( ${{ inputs.geminicli-timeout }} * 60 )) gemini $MODEL_ARG --yolo -p "/security-review" > "$RESULTS_FILE" 2>&1
        EXIT_CODE=$?

        echo "results_file=$RESULTS_FILE" >> $GITHUB_OUTPUT

        HIGH_COUNT=$(grep -c "Severity: High" "$RESULTS_FILE" 2>/dev/null || echo "0")
        MED_COUNT=$(grep -c "Severity: Medium" "$RESULTS_FILE" 2>/dev/null || echo "0")
        FINDINGS_COUNT=$(( ${HIGH_COUNT:-0} + ${MED_COUNT:-0} ))
        echo "findings_count=$FINDINGS_COUNT" >> $GITHUB_OUTPUT

        exit $EXIT_CODE

    - name: Use cached results
      id: use-cache
      if: steps.check-cache.outputs.cache_hit == 'true'
      shell: bash
      run: |
        echo "results_file=${{ steps.check-cache.outputs.cache_file }}" >> $GITHUB_OUTPUT
        HIGH_COUNT=$(grep -c "Severity: High" "${{ steps.check-cache.outputs.cache_file }}" 2>/dev/null || echo "0")
        MED_COUNT=$(grep -c "Severity: Medium" "${{ steps.check-cache.outputs.cache_file }}" 2>/dev/null || echo "0")
        FINDINGS_COUNT=$(( ${HIGH_COUNT:-0} + ${MED_COUNT:-0} ))
        echo "findings_count=$FINDINGS_COUNT" >> $GITHUB_OUTPUT

    - name: Upload results as artifact
      if: inputs.upload-results == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: gemini-security-review-results
        path: ${{ steps.geminicli-scan.outputs.results_file || steps.use-cache.outputs.results_file }}
        retention-days: 30

    - name: Comment on PR
      if: inputs.comment-pr == 'true' && github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const resultsFile = '${{ steps.geminicli-scan.outputs.results_file || steps.use-cache.outputs.results_file }}';

          let content;
          try {
            content = fs.readFileSync(resultsFile, 'utf8').trim();
          } catch (e) {
            console.log('Could not read results file:', e.message);
            return;
          }

          const body = [
            '## 🛡️ Gemini Security Review',
            '',
            content,
            '',
            '*Powered by [Gemini Code Security Reviewer](https://github.com/your-org/gemini-code-security-review)*'
          ].join('\n');

          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body
          });

branding:
  icon: 'shield'
  color: 'blue'
